#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path: /
    controller: App\Controller\HomeController::index

order:
    path: /order
    controller: App\Controller\HomeController::order