#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path: /
    controller: App\Controller\HomeController::index

order:
    path: /order
    controller: App\Controller\HomeController::order

order_success:
    path: /order_success
    controller: App\Controller\HomeController::order_success
