#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path: /
    controller: App\Controller\HomeController::index

order:
    path: /order
    controller: App\Controller\HomeController::order

order/success:
    path: /order/success
    controller: App\Controller\HomeController::order_success
